name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug - Check File Structure
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          else
            echo "❌ package.json NOT FOUND!"
            exit 1
          fi

      - name: Run Tests
        run: npm test

      - name: Set Execute Permission for Deploy Script
        run: chmod +x ./scripts/docker-deploy.sh

      - name: Deploy Application
        if: github.ref == 'refs/heads/main'
        run: ./scripts/docker-deploy.sh
